### ISSUE TITLE
Move to Database from Connection in Statement Implementations

### ISSUE THREAD

**Issue by alexandru-slobodcicov** [liquibase/liquibase-mongodb#67]
In order to be closer to CustomChange implementations and have more generic Abstract Classes would be better to operate with Database Implementations instead of Connection Implementations passed to Statements/Executor etc.

┆Issue is synchronized with this [Jira Bug](https://datical.atlassian.net/browse/LB-1017) by [Unito](https://www.unito.io/learn-more)

**Comment by jsonking** [comment]
@alexandru-slobodcicov I'm thinking that the Statement implementations could execute the `runCommand` operation instead of the higher level driver helper methods.
There are two principal benefits:

1: options can be specified in the migrations themselves and are passed through to the database directly. No need to manually add support for options that change over time.

2: Works with a larger set of underlying mongo-driver versions; increasing adoption of this library.

Example: `liquibase.ext.mongodb.statement.InsertOneStatement`
**Current Code:**
```
@Override
public void execute(final MongoConnection connection) {
    final MongoCollection<Document> collection = connection.getDatabase().getCollection(getCollectionName());
    collection.insertOne(document);
}
```
Note that the current code doesn't support any options!

**Modified Code:**
```
@Override
public void execute(final MongoConnection connection) {
    Bson bson = createCommand();
    connection.getDatabase().runCommand(bson);
}

private Bson createCommand() {
    Document command = new Document("insert", getCollectionName());
    command.put("documents", Collections.singletonList(document));
    command.putAll(options);
    return command.toBsonDocument(Document.class, getDefaultCodecRegistry());
}
```

This is the strategy I used in PR https://github.com/liquibase/liquibase-mongodb/pull/78 to add support for all options in the `CreateCollectionStatement` class

Finally there are currently two open issues (https://github.com/liquibase/liquibase-mongodb/issues/71 and https://github.com/liquibase/liquibase-mongodb/issues/80) relating to supporting the latest driver version.

The signature of the `runCommand` methods in the driver has not changed between version `3.12.x` and `4.x`; but `collection.insertOne` is no longer `void` and therefore fails at runtime. i.e using `runCommand` is a more stable interface to use and would provide greater chances of forward-compatibility.

Keen to hear your thoughts?

Jason

**Comment by alexandru-slobodcicov** [comment]
Hi @jsonking. Indeed worth changing where possible the Statemens to db.runCommand as you did for CreateCollectionStatement. Just want to mention that the initial approach was to stick to driver APIs until we identified that approximatively everything can be done from runCommand and adminCommand. The same is mentioned in README: A couple of Changes were implemented until identified that majority of the operations can be achieved using `db.runCommand()` and `db.adminCommand()`. So there is already the option to define runCommand and adminCommand in changesets with all the flexibility. 

This particular issue is about having the Database instead of Connection in statements: 
`execute(final MongoConnection connection)` -> `execute(final MongoLiquibaseDatabase database)`
